title: 'Nataz Restaurant '
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7771804
  brandStrength: 0
  lightness: 0.8560334
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  rhythmicContrast: 0.6792114
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Nataz Restaurant
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.81944
layout_spectrum: 0.889
